### ISSUE TITLE
Print statement specificity for pre-populated lookup tables

### ISSUE THREAD

**Issue by CBroz1** [datajoint-company/datajoint-utilities#3]
Future feature: skip lookup tables or indicate destination already populated within print statement.

In trying out `db_migration`, I presumed an error when `AcquisitionSoftware` registered 0/0 records uploaded. I think is table is populated on activation with `contents = zip(['SpikeGLX', 'Open Ephys'])`. We could either skip this tables or indicate to the user that these tables match and therefore don't need to be migrated.

```db_migration.migrate_schema(source_schema, target_schema)
Data migration for schema: neuro_scan
	Data migration for table AcquisitionSoftware: 0/0 records
	Data migration for table Channel: 0/0 records
	Data migration for table Scan: 1/1 records
	Data migration for table ScanInfo: 1/1 records
	Data migration for table Field: 4/4 records
	Data migration for table ScanFile: 1/1 records
	Data migration for table ScanLocation: 0/0 records
--- Total records migrated: 7/7 records ---
```

**Comment by ttngu207** [comment]
Thanks for testing @CBroz1. 
In your testing, it is the case that the `AcquisitionSoftware` table are having the same `contents`, however we cannot rely on all lookup tables to always have the same set of entries. This is only true if users are very diligent with updating the `contents` field in the code, however, most often time users will just insert/delete entries from lookup tables without updating the code correspondingly.
Migrating entries for lookup tables is still very much needed.
